// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/salon.proto

package salon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSalonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSalonRequest) Reset() {
	*x = AddSalonRequest{}
	mi := &file_proto_salon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSalonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSalonRequest) ProtoMessage() {}

func (x *AddSalonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSalonRequest.ProtoReflect.Descriptor instead.
func (*AddSalonRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{0}
}

func (x *AddSalonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSalonRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type AddProcedureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalonId       string                 `protobuf:"bytes,1,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProcedureRequest) Reset() {
	*x = AddProcedureRequest{}
	mi := &file_proto_salon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProcedureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProcedureRequest) ProtoMessage() {}

func (x *AddProcedureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProcedureRequest.ProtoReflect.Descriptor instead.
func (*AddProcedureRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{1}
}

func (x *AddProcedureRequest) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *AddProcedureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProcedureRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type AddSpecialistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalonId       string                 `protobuf:"bytes,1,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpecialistRequest) Reset() {
	*x = AddSpecialistRequest{}
	mi := &file_proto_salon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpecialistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpecialistRequest) ProtoMessage() {}

func (x *AddSpecialistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpecialistRequest.ProtoReflect.Descriptor instead.
func (*AddSpecialistRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{2}
}

func (x *AddSpecialistRequest) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *AddSpecialistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SalonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalonResponse) Reset() {
	*x = SalonResponse{}
	mi := &file_proto_salon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalonResponse) ProtoMessage() {}

func (x *SalonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalonResponse.ProtoReflect.Descriptor instead.
func (*SalonResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{3}
}

func (x *SalonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SalonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SalonResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ProcedureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SalonId       string                 `protobuf:"bytes,2,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureResponse) Reset() {
	*x = ProcedureResponse{}
	mi := &file_proto_salon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResponse) ProtoMessage() {}

func (x *ProcedureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResponse.ProtoReflect.Descriptor instead.
func (*ProcedureResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{4}
}

func (x *ProcedureResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcedureResponse) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *ProcedureResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcedureResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SpecialistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SalonId       string                 `protobuf:"bytes,2,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialistResponse) Reset() {
	*x = SpecialistResponse{}
	mi := &file_proto_salon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialistResponse) ProtoMessage() {}

func (x *SpecialistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialistResponse.ProtoReflect.Descriptor instead.
func (*SpecialistResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{5}
}

func (x *SpecialistResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpecialistResponse) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *SpecialistResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_salon_proto protoreflect.FileDescriptor

const file_proto_salon_proto_rawDesc = "" +
	"\n" +
	"\x11proto/salon.proto\x12\x05salon\"A\n" +
	"\x0fAddSalonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"`\n" +
	"\x13AddProcedureRequest\x12\x19\n" +
	"\bsalon_id\x18\x01 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\"E\n" +
	"\x14AddSpecialistRequest\x12\x19\n" +
	"\bsalon_id\x18\x01 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"O\n" +
	"\rSalonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"n\n" +
	"\x11ProcedureResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bsalon_id\x18\x02 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\"S\n" +
	"\x12SpecialistResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bsalon_id\x18\x02 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name2\xd7\x01\n" +
	"\fSalonService\x128\n" +
	"\bAddSalon\x12\x16.salon.AddSalonRequest\x1a\x14.salon.SalonResponse\x12D\n" +
	"\fAddProcedure\x12\x1a.salon.AddProcedureRequest\x1a\x18.salon.ProcedureResponse\x12G\n" +
	"\rAddSpecialist\x12\x1b.salon.AddSpecialistRequest\x1a\x19.salon.SpecialistResponseB\x0fZ\r./proto;salonb\x06proto3"

var (
	file_proto_salon_proto_rawDescOnce sync.Once
	file_proto_salon_proto_rawDescData []byte
)

func file_proto_salon_proto_rawDescGZIP() []byte {
	file_proto_salon_proto_rawDescOnce.Do(func() {
		file_proto_salon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_salon_proto_rawDesc), len(file_proto_salon_proto_rawDesc)))
	})
	return file_proto_salon_proto_rawDescData
}

var file_proto_salon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_salon_proto_goTypes = []any{
	(*AddSalonRequest)(nil),      // 0: salon.AddSalonRequest
	(*AddProcedureRequest)(nil),  // 1: salon.AddProcedureRequest
	(*AddSpecialistRequest)(nil), // 2: salon.AddSpecialistRequest
	(*SalonResponse)(nil),        // 3: salon.SalonResponse
	(*ProcedureResponse)(nil),    // 4: salon.ProcedureResponse
	(*SpecialistResponse)(nil),   // 5: salon.SpecialistResponse
}
var file_proto_salon_proto_depIdxs = []int32{
	0, // 0: salon.SalonService.AddSalon:input_type -> salon.AddSalonRequest
	1, // 1: salon.SalonService.AddProcedure:input_type -> salon.AddProcedureRequest
	2, // 2: salon.SalonService.AddSpecialist:input_type -> salon.AddSpecialistRequest
	3, // 3: salon.SalonService.AddSalon:output_type -> salon.SalonResponse
	4, // 4: salon.SalonService.AddProcedure:output_type -> salon.ProcedureResponse
	5, // 5: salon.SalonService.AddSpecialist:output_type -> salon.SpecialistResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_salon_proto_init() }
func file_proto_salon_proto_init() {
	if File_proto_salon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_salon_proto_rawDesc), len(file_proto_salon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_salon_proto_goTypes,
		DependencyIndexes: file_proto_salon_proto_depIdxs,
		MessageInfos:      file_proto_salon_proto_msgTypes,
	}.Build()
	File_proto_salon_proto = out.File
	file_proto_salon_proto_goTypes = nil
	file_proto_salon_proto_depIdxs = nil
}
