// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/salon.proto

package salon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_salon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{0}
}

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_proto_salon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{1}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddSalonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSalonRequest) Reset() {
	*x = AddSalonRequest{}
	mi := &file_proto_salon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSalonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSalonRequest) ProtoMessage() {}

func (x *AddSalonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSalonRequest.ProtoReflect.Descriptor instead.
func (*AddSalonRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{2}
}

func (x *AddSalonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSalonRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UpdateSalonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSalonRequest) Reset() {
	*x = UpdateSalonRequest{}
	mi := &file_proto_salon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSalonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSalonRequest) ProtoMessage() {}

func (x *UpdateSalonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSalonRequest.ProtoReflect.Descriptor instead.
func (*UpdateSalonRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSalonRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSalonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSalonRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type SalonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalonResponse) Reset() {
	*x = SalonResponse{}
	mi := &file_proto_salon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalonResponse) ProtoMessage() {}

func (x *SalonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalonResponse.ProtoReflect.Descriptor instead.
func (*SalonResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{4}
}

func (x *SalonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SalonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SalonResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type SalonListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salons        []*SalonResponse       `protobuf:"bytes,1,rep,name=salons,proto3" json:"salons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalonListResponse) Reset() {
	*x = SalonListResponse{}
	mi := &file_proto_salon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalonListResponse) ProtoMessage() {}

func (x *SalonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalonListResponse.ProtoReflect.Descriptor instead.
func (*SalonListResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{5}
}

func (x *SalonListResponse) GetSalons() []*SalonResponse {
	if x != nil {
		return x.Salons
	}
	return nil
}

type AddProcedureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalonId       string                 `protobuf:"bytes,1,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProcedureRequest) Reset() {
	*x = AddProcedureRequest{}
	mi := &file_proto_salon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProcedureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProcedureRequest) ProtoMessage() {}

func (x *AddProcedureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProcedureRequest.ProtoReflect.Descriptor instead.
func (*AddProcedureRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{6}
}

func (x *AddProcedureRequest) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *AddProcedureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProcedureRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AddProcedureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProcedureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SalonId       string                 `protobuf:"bytes,5,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProcedureRequest) Reset() {
	*x = UpdateProcedureRequest{}
	mi := &file_proto_salon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProcedureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcedureRequest) ProtoMessage() {}

func (x *UpdateProcedureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcedureRequest.ProtoReflect.Descriptor instead.
func (*UpdateProcedureRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProcedureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProcedureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProcedureRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateProcedureRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProcedureRequest) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

type ProcedureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SalonId       string                 `protobuf:"bytes,2,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureResponse) Reset() {
	*x = ProcedureResponse{}
	mi := &file_proto_salon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResponse) ProtoMessage() {}

func (x *ProcedureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResponse.ProtoReflect.Descriptor instead.
func (*ProcedureResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{8}
}

func (x *ProcedureResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcedureResponse) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *ProcedureResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcedureResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ProcedureResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ProcedureListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Procedures    []*ProcedureResponse   `protobuf:"bytes,1,rep,name=procedures,proto3" json:"procedures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureListResponse) Reset() {
	*x = ProcedureListResponse{}
	mi := &file_proto_salon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureListResponse) ProtoMessage() {}

func (x *ProcedureListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureListResponse.ProtoReflect.Descriptor instead.
func (*ProcedureListResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{9}
}

func (x *ProcedureListResponse) GetProcedures() []*ProcedureResponse {
	if x != nil {
		return x.Procedures
	}
	return nil
}

type AddSpecialistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalonId       string                 `protobuf:"bytes,1,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSpecialistRequest) Reset() {
	*x = AddSpecialistRequest{}
	mi := &file_proto_salon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSpecialistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSpecialistRequest) ProtoMessage() {}

func (x *AddSpecialistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSpecialistRequest.ProtoReflect.Descriptor instead.
func (*AddSpecialistRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{10}
}

func (x *AddSpecialistRequest) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *AddSpecialistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSpecialistRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateSpecialistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	SalonId       string                 `protobuf:"bytes,4,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpecialistRequest) Reset() {
	*x = UpdateSpecialistRequest{}
	mi := &file_proto_salon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpecialistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecialistRequest) ProtoMessage() {}

func (x *UpdateSpecialistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecialistRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpecialistRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSpecialistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSpecialistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSpecialistRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateSpecialistRequest) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

type SpecialistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SalonId       string                 `protobuf:"bytes,2,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialistResponse) Reset() {
	*x = SpecialistResponse{}
	mi := &file_proto_salon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialistResponse) ProtoMessage() {}

func (x *SpecialistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialistResponse.ProtoReflect.Descriptor instead.
func (*SpecialistResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{12}
}

func (x *SpecialistResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpecialistResponse) GetSalonId() string {
	if x != nil {
		return x.SalonId
	}
	return ""
}

func (x *SpecialistResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpecialistResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type SpecialistListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialists   []*SpecialistResponse  `protobuf:"bytes,1,rep,name=specialists,proto3" json:"specialists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialistListResponse) Reset() {
	*x = SpecialistListResponse{}
	mi := &file_proto_salon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialistListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialistListResponse) ProtoMessage() {}

func (x *SpecialistListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialistListResponse.ProtoReflect.Descriptor instead.
func (*SpecialistListResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{13}
}

func (x *SpecialistListResponse) GetSpecialists() []*SpecialistResponse {
	if x != nil {
		return x.Specialists
	}
	return nil
}

type AssignProcedureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecialistId  string                 `protobuf:"bytes,1,opt,name=specialist_id,json=specialistId,proto3" json:"specialist_id,omitempty"`
	ProcedureId   string                 `protobuf:"bytes,2,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignProcedureRequest) Reset() {
	*x = AssignProcedureRequest{}
	mi := &file_proto_salon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignProcedureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignProcedureRequest) ProtoMessage() {}

func (x *AssignProcedureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignProcedureRequest.ProtoReflect.Descriptor instead.
func (*AssignProcedureRequest) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{14}
}

func (x *AssignProcedureRequest) GetSpecialistId() string {
	if x != nil {
		return x.SpecialistId
	}
	return ""
}

func (x *AssignProcedureRequest) GetProcedureId() string {
	if x != nil {
		return x.ProcedureId
	}
	return ""
}

type AssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignResponse) Reset() {
	*x = AssignResponse{}
	mi := &file_proto_salon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignResponse) ProtoMessage() {}

func (x *AssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignResponse.ProtoReflect.Descriptor instead.
func (*AssignResponse) Descriptor() ([]byte, []int) {
	return file_proto_salon_proto_rawDescGZIP(), []int{15}
}

func (x *AssignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_salon_proto protoreflect.FileDescriptor

const file_proto_salon_proto_rawDesc = "" +
	"\n" +
	"\x11proto/salon.proto\x12\x05salon\"\a\n" +
	"\x05Empty\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x0fAddSalonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"T\n" +
	"\x12UpdateSalonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"O\n" +
	"\rSalonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"A\n" +
	"\x11SalonListResponse\x12,\n" +
	"\x06salons\x18\x01 \x03(\v2\x14.salon.SalonResponseR\x06salons\"\x82\x01\n" +
	"\x13AddProcedureRequest\x12\x19\n" +
	"\bsalon_id\x18\x01 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x95\x01\n" +
	"\x16UpdateProcedureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bsalon_id\x18\x05 \x01(\tR\asalonId\"\x90\x01\n" +
	"\x11ProcedureResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bsalon_id\x18\x02 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"Q\n" +
	"\x15ProcedureListResponse\x128\n" +
	"\n" +
	"procedures\x18\x01 \x03(\v2\x18.salon.ProcedureResponseR\n" +
	"procedures\"W\n" +
	"\x14AddSpecialistRequest\x12\x19\n" +
	"\bsalon_id\x18\x01 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\"j\n" +
	"\x17UpdateSpecialistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x19\n" +
	"\bsalon_id\x18\x04 \x01(\tR\asalonId\"e\n" +
	"\x12SpecialistResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bsalon_id\x18\x02 \x01(\tR\asalonId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\"U\n" +
	"\x16SpecialistListResponse\x12;\n" +
	"\vspecialists\x18\x01 \x03(\v2\x19.salon.SpecialistResponseR\vspecialists\"`\n" +
	"\x16AssignProcedureRequest\x12#\n" +
	"\rspecialist_id\x18\x01 \x01(\tR\fspecialistId\x12!\n" +
	"\fprocedure_id\x18\x02 \x01(\tR\vprocedureId\"*\n" +
	"\x0eAssignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x84\a\n" +
	"\fSalonService\x128\n" +
	"\bAddSalon\x12\x16.salon.AddSalonRequest\x1a\x14.salon.SalonResponse\x12D\n" +
	"\fAddProcedure\x12\x1a.salon.AddProcedureRequest\x1a\x18.salon.ProcedureResponse\x12G\n" +
	"\rAddSpecialist\x12\x1b.salon.AddSpecialistRequest\x1a\x19.salon.SpecialistResponse\x126\n" +
	"\vUpdateSalon\x12\x19.salon.UpdateSalonRequest\x1a\f.salon.Empty\x12-\n" +
	"\vDeleteSalon\x12\x10.salon.IdRequest\x1a\f.salon.Empty\x126\n" +
	"\fGetAllSalons\x12\f.salon.Empty\x1a\x18.salon.SalonListResponse\x12>\n" +
	"\x0fUpdateProcedure\x12\x1d.salon.UpdateProcedureRequest\x1a\f.salon.Empty\x121\n" +
	"\x0fDeleteProcedure\x12\x10.salon.IdRequest\x1a\f.salon.Empty\x12@\n" +
	"\x10UpdateSpecialist\x12\x1e.salon.UpdateSpecialistRequest\x1a\f.salon.Empty\x122\n" +
	"\x10DeleteSpecialist\x12\x10.salon.IdRequest\x1a\f.salon.Empty\x12@\n" +
	"\x11GetAllSpecialists\x12\f.salon.Empty\x1a\x1d.salon.SpecialistListResponse\x12>\n" +
	"\x10GetAllProcedures\x12\f.salon.Empty\x1a\x1c.salon.ProcedureListResponse\x12S\n" +
	"\x1bAssignProcedureToSpecialist\x12\x1d.salon.AssignProcedureRequest\x1a\x15.salon.AssignResponse\x12L\n" +
	"\x1dRemoveProcedureFromSpecialist\x12\x1d.salon.AssignProcedureRequest\x1a\f.salon.EmptyBDZBgithub.com/gemdivk/LUMERA-SPA/salon-management-service/proto;salonb\x06proto3"

var (
	file_proto_salon_proto_rawDescOnce sync.Once
	file_proto_salon_proto_rawDescData []byte
)

func file_proto_salon_proto_rawDescGZIP() []byte {
	file_proto_salon_proto_rawDescOnce.Do(func() {
		file_proto_salon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_salon_proto_rawDesc), len(file_proto_salon_proto_rawDesc)))
	})
	return file_proto_salon_proto_rawDescData
}

var file_proto_salon_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_salon_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: salon.Empty
	(*IdRequest)(nil),               // 1: salon.IdRequest
	(*AddSalonRequest)(nil),         // 2: salon.AddSalonRequest
	(*UpdateSalonRequest)(nil),      // 3: salon.UpdateSalonRequest
	(*SalonResponse)(nil),           // 4: salon.SalonResponse
	(*SalonListResponse)(nil),       // 5: salon.SalonListResponse
	(*AddProcedureRequest)(nil),     // 6: salon.AddProcedureRequest
	(*UpdateProcedureRequest)(nil),  // 7: salon.UpdateProcedureRequest
	(*ProcedureResponse)(nil),       // 8: salon.ProcedureResponse
	(*ProcedureListResponse)(nil),   // 9: salon.ProcedureListResponse
	(*AddSpecialistRequest)(nil),    // 10: salon.AddSpecialistRequest
	(*UpdateSpecialistRequest)(nil), // 11: salon.UpdateSpecialistRequest
	(*SpecialistResponse)(nil),      // 12: salon.SpecialistResponse
	(*SpecialistListResponse)(nil),  // 13: salon.SpecialistListResponse
	(*AssignProcedureRequest)(nil),  // 14: salon.AssignProcedureRequest
	(*AssignResponse)(nil),          // 15: salon.AssignResponse
}
var file_proto_salon_proto_depIdxs = []int32{
	4,  // 0: salon.SalonListResponse.salons:type_name -> salon.SalonResponse
	8,  // 1: salon.ProcedureListResponse.procedures:type_name -> salon.ProcedureResponse
	12, // 2: salon.SpecialistListResponse.specialists:type_name -> salon.SpecialistResponse
	2,  // 3: salon.SalonService.AddSalon:input_type -> salon.AddSalonRequest
	6,  // 4: salon.SalonService.AddProcedure:input_type -> salon.AddProcedureRequest
	10, // 5: salon.SalonService.AddSpecialist:input_type -> salon.AddSpecialistRequest
	3,  // 6: salon.SalonService.UpdateSalon:input_type -> salon.UpdateSalonRequest
	1,  // 7: salon.SalonService.DeleteSalon:input_type -> salon.IdRequest
	0,  // 8: salon.SalonService.GetAllSalons:input_type -> salon.Empty
	7,  // 9: salon.SalonService.UpdateProcedure:input_type -> salon.UpdateProcedureRequest
	1,  // 10: salon.SalonService.DeleteProcedure:input_type -> salon.IdRequest
	11, // 11: salon.SalonService.UpdateSpecialist:input_type -> salon.UpdateSpecialistRequest
	1,  // 12: salon.SalonService.DeleteSpecialist:input_type -> salon.IdRequest
	0,  // 13: salon.SalonService.GetAllSpecialists:input_type -> salon.Empty
	0,  // 14: salon.SalonService.GetAllProcedures:input_type -> salon.Empty
	14, // 15: salon.SalonService.AssignProcedureToSpecialist:input_type -> salon.AssignProcedureRequest
	14, // 16: salon.SalonService.RemoveProcedureFromSpecialist:input_type -> salon.AssignProcedureRequest
	4,  // 17: salon.SalonService.AddSalon:output_type -> salon.SalonResponse
	8,  // 18: salon.SalonService.AddProcedure:output_type -> salon.ProcedureResponse
	12, // 19: salon.SalonService.AddSpecialist:output_type -> salon.SpecialistResponse
	0,  // 20: salon.SalonService.UpdateSalon:output_type -> salon.Empty
	0,  // 21: salon.SalonService.DeleteSalon:output_type -> salon.Empty
	5,  // 22: salon.SalonService.GetAllSalons:output_type -> salon.SalonListResponse
	0,  // 23: salon.SalonService.UpdateProcedure:output_type -> salon.Empty
	0,  // 24: salon.SalonService.DeleteProcedure:output_type -> salon.Empty
	0,  // 25: salon.SalonService.UpdateSpecialist:output_type -> salon.Empty
	0,  // 26: salon.SalonService.DeleteSpecialist:output_type -> salon.Empty
	13, // 27: salon.SalonService.GetAllSpecialists:output_type -> salon.SpecialistListResponse
	9,  // 28: salon.SalonService.GetAllProcedures:output_type -> salon.ProcedureListResponse
	15, // 29: salon.SalonService.AssignProcedureToSpecialist:output_type -> salon.AssignResponse
	0,  // 30: salon.SalonService.RemoveProcedureFromSpecialist:output_type -> salon.Empty
	17, // [17:31] is the sub-list for method output_type
	3,  // [3:17] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_salon_proto_init() }
func file_proto_salon_proto_init() {
	if File_proto_salon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_salon_proto_rawDesc), len(file_proto_salon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_salon_proto_goTypes,
		DependencyIndexes: file_proto_salon_proto_depIdxs,
		MessageInfos:      file_proto_salon_proto_msgTypes,
	}.Build()
	File_proto_salon_proto = out.File
	file_proto_salon_proto_goTypes = nil
	file_proto_salon_proto_depIdxs = nil
}
