// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== CLIENT =====
type ListAvailableSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcedureId   string                 `protobuf:"bytes,1,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // "YYYY-MM-DD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableSlotsRequest) Reset() {
	*x = ListAvailableSlotsRequest{}
	mi := &file_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableSlotsRequest) ProtoMessage() {}

func (x *ListAvailableSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableSlotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *ListAvailableSlotsRequest) GetProcedureId() string {
	if x != nil {
		return x.ProcedureId
	}
	return ""
}

func (x *ListAvailableSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type TimeSlot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpecialistId   string                 `protobuf:"bytes,1,opt,name=specialist_id,json=specialistId,proto3" json:"specialist_id,omitempty"`
	SpecialistName string                 `protobuf:"bytes,2,opt,name=specialist_name,json=specialistName,proto3" json:"specialist_name,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSlot) GetSpecialistId() string {
	if x != nil {
		return x.SpecialistId
	}
	return ""
}

func (x *TimeSlot) GetSpecialistName() string {
	if x != nil {
		return x.SpecialistName
	}
	return ""
}

func (x *TimeSlot) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TimeSlot) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ListAvailableSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*TimeSlot            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableSlotsResponse) Reset() {
	*x = ListAvailableSlotsResponse{}
	mi := &file_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableSlotsResponse) ProtoMessage() {}

func (x *ListAvailableSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableSlotsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableSlotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ListAvailableSlotsResponse) GetSlots() []*TimeSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SpecialistId  string                 `protobuf:"bytes,2,opt,name=specialist_id,json=specialistId,proto3" json:"specialist_id,omitempty"`
	ProcedureId   string                 `protobuf:"bytes,3,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBookingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateBookingRequest) GetSpecialistId() string {
	if x != nil {
		return x.SpecialistId
	}
	return ""
}

func (x *CreateBookingRequest) GetProcedureId() string {
	if x != nil {
		return x.ProcedureId
	}
	return ""
}

func (x *CreateBookingRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

type BookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingResponse) Reset() {
	*x = BookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingResponse) ProtoMessage() {}

func (x *BookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingResponse.ProtoReflect.Descriptor instead.
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *BookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *BookingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClientBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientBookingsRequest) Reset() {
	*x = ClientBookingsRequest{}
	mi := &file_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBookingsRequest) ProtoMessage() {}

func (x *ClientBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBookingsRequest.ProtoReflect.Descriptor instead.
func (*ClientBookingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *ClientBookingsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Booking struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcedureName  string                 `protobuf:"bytes,2,opt,name=procedure_name,json=procedureName,proto3" json:"procedure_name,omitempty"`
	SpecialistName string                 `protobuf:"bytes,3,opt,name=specialist_name,json=specialistName,proto3" json:"specialist_name,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetProcedureName() string {
	if x != nil {
		return x.ProcedureName
	}
	return ""
}

func (x *Booking) GetSpecialistName() string {
	if x != nil {
		return x.SpecialistName
	}
	return ""
}

func (x *Booking) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Booking) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClientBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientBookingsResponse) Reset() {
	*x = ClientBookingsResponse{}
	mi := &file_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBookingsResponse) ProtoMessage() {}

func (x *ClientBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBookingsResponse.ProtoReflect.Descriptor instead.
func (*ClientBookingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *ClientBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

// ===== ADMIN =====
type CreateProcedureRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateProcedureRequest) Reset() {
	*x = CreateProcedureRequest{}
	mi := &file_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcedureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcedureRequest) ProtoMessage() {}

func (x *CreateProcedureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcedureRequest.ProtoReflect.Descriptor instead.
func (*CreateProcedureRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *CreateProcedureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProcedureRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type ProcedureResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcedureResponse) Reset() {
	*x = ProcedureResponse{}
	mi := &file_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResponse) ProtoMessage() {}

func (x *ProcedureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResponse.ProtoReflect.Descriptor instead.
func (*ProcedureResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *ProcedureResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcedureResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcedureResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type AssignProcedureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecialistId  string                 `protobuf:"bytes,1,opt,name=specialist_id,json=specialistId,proto3" json:"specialist_id,omitempty"`
	ProcedureId   string                 `protobuf:"bytes,2,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignProcedureRequest) Reset() {
	*x = AssignProcedureRequest{}
	mi := &file_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignProcedureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignProcedureRequest) ProtoMessage() {}

func (x *AssignProcedureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignProcedureRequest.ProtoReflect.Descriptor instead.
func (*AssignProcedureRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{12}
}

func (x *AssignProcedureRequest) GetSpecialistId() string {
	if x != nil {
		return x.SpecialistId
	}
	return ""
}

func (x *AssignProcedureRequest) GetProcedureId() string {
	if x != nil {
		return x.ProcedureId
	}
	return ""
}

type AssignProcedureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignProcedureResponse) Reset() {
	*x = AssignProcedureResponse{}
	mi := &file_proto_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignProcedureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignProcedureResponse) ProtoMessage() {}

func (x *AssignProcedureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignProcedureResponse.ProtoReflect.Descriptor instead.
func (*AssignProcedureResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{13}
}

func (x *AssignProcedureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateScheduleTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecialistId  string                 `protobuf:"bytes,1,opt,name=specialist_id,json=specialistId,proto3" json:"specialist_id,omitempty"`
	Weekday       int32                  `protobuf:"varint,2,opt,name=weekday,proto3" json:"weekday,omitempty"`                     // 0=Sunday, 1=Monday, ...
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "09:00"
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "17:00"
	BreakMinutes  int32                  `protobuf:"varint,5,opt,name=break_minutes,json=breakMinutes,proto3" json:"break_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleTemplateRequest) Reset() {
	*x = CreateScheduleTemplateRequest{}
	mi := &file_proto_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleTemplateRequest) ProtoMessage() {}

func (x *CreateScheduleTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{14}
}

func (x *CreateScheduleTemplateRequest) GetSpecialistId() string {
	if x != nil {
		return x.SpecialistId
	}
	return ""
}

func (x *CreateScheduleTemplateRequest) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *CreateScheduleTemplateRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateScheduleTemplateRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateScheduleTemplateRequest) GetBreakMinutes() int32 {
	if x != nil {
		return x.BreakMinutes
	}
	return 0
}

type ScheduleTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTemplateResponse) Reset() {
	*x = ScheduleTemplateResponse{}
	mi := &file_proto_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTemplateResponse) ProtoMessage() {}

func (x *ScheduleTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTemplateResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{15}
}

func (x *ScheduleTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OverrideDayScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecialistId  string                 `protobuf:"bytes,1,opt,name=specialist_id,json=specialistId,proto3" json:"specialist_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                            // "YYYY-MM-DD"
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "10:00"
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "15:00"
	IsCancelled   bool                   `protobuf:"varint,5,opt,name=is_cancelled,json=isCancelled,proto3" json:"is_cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideDayScheduleRequest) Reset() {
	*x = OverrideDayScheduleRequest{}
	mi := &file_proto_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideDayScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideDayScheduleRequest) ProtoMessage() {}

func (x *OverrideDayScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideDayScheduleRequest.ProtoReflect.Descriptor instead.
func (*OverrideDayScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{16}
}

func (x *OverrideDayScheduleRequest) GetSpecialistId() string {
	if x != nil {
		return x.SpecialistId
	}
	return ""
}

func (x *OverrideDayScheduleRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *OverrideDayScheduleRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *OverrideDayScheduleRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *OverrideDayScheduleRequest) GetIsCancelled() bool {
	if x != nil {
		return x.IsCancelled
	}
	return false
}

type OverrideDayScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideDayScheduleResponse) Reset() {
	*x = OverrideDayScheduleResponse{}
	mi := &file_proto_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideDayScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideDayScheduleResponse) ProtoMessage() {}

func (x *OverrideDayScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideDayScheduleResponse.ProtoReflect.Descriptor instead.
func (*OverrideDayScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{17}
}

func (x *OverrideDayScheduleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_booking_proto protoreflect.FileDescriptor

const file_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x13proto/booking.proto\x12\abooking\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"R\n" +
	"\x19ListAvailableSlotsRequest\x12!\n" +
	"\fprocedure_id\x18\x01 \x01(\tR\vprocedureId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"\xca\x01\n" +
	"\bTimeSlot\x12#\n" +
	"\rspecialist_id\x18\x01 \x01(\tR\fspecialistId\x12'\n" +
	"\x0fspecialist_name\x18\x02 \x01(\tR\x0especialistName\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"E\n" +
	"\x1aListAvailableSlotsResponse\x12'\n" +
	"\x05slots\x18\x01 \x03(\v2\x11.booking.TimeSlotR\x05slots\"\xb6\x01\n" +
	"\x14CreateBookingRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rspecialist_id\x18\x02 \x01(\tR\fspecialistId\x12!\n" +
	"\fprocedure_id\x18\x03 \x01(\tR\vprocedureId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"H\n" +
	"\x0fBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"1\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x15ClientBookingsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xf3\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eprocedure_name\x18\x02 \x01(\tR\rprocedureName\x12'\n" +
	"\x0fspecialist_name\x18\x03 \x01(\tR\x0especialistName\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"F\n" +
	"\x16ClientBookingsResponse\x12,\n" +
	"\bbookings\x18\x01 \x03(\v2\x10.booking.BookingR\bbookings\"W\n" +
	"\x16CreateProcedureRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\"b\n" +
	"\x11ProcedureResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\"`\n" +
	"\x16AssignProcedureRequest\x12#\n" +
	"\rspecialist_id\x18\x01 \x01(\tR\fspecialistId\x12!\n" +
	"\fprocedure_id\x18\x02 \x01(\tR\vprocedureId\"3\n" +
	"\x17AssignProcedureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbd\x01\n" +
	"\x1dCreateScheduleTemplateRequest\x12#\n" +
	"\rspecialist_id\x18\x01 \x01(\tR\fspecialistId\x12\x18\n" +
	"\aweekday\x18\x02 \x01(\x05R\aweekday\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12#\n" +
	"\rbreak_minutes\x18\x05 \x01(\x05R\fbreakMinutes\"4\n" +
	"\x18ScheduleTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x01\n" +
	"\x1aOverrideDayScheduleRequest\x12#\n" +
	"\rspecialist_id\x18\x01 \x01(\tR\fspecialistId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12!\n" +
	"\fis_cancelled\x18\x05 \x01(\bR\visCancelled\"7\n" +
	"\x1bOverrideDayScheduleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe1\x05\n" +
	"\x0eBookingService\x12]\n" +
	"\x12ListAvailableSlots\x12\".booking.ListAvailableSlotsRequest\x1a#.booking.ListAvailableSlotsResponse\x12H\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x18.booking.BookingResponse\x12N\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x1e.booking.CancelBookingResponse\x12U\n" +
	"\x12ListClientBookings\x12\x1e.booking.ClientBookingsRequest\x1a\x1f.booking.ClientBookingsResponse\x12S\n" +
	"\x14AdminCreateProcedure\x12\x1f.booking.CreateProcedureRequest\x1a\x1a.booking.ProcedureResponse\x12Y\n" +
	"\x14AdminAssignProcedure\x12\x1f.booking.AssignProcedureRequest\x1a .booking.AssignProcedureResponse\x12h\n" +
	"\x1bAdminCreateScheduleTemplate\x12&.booking.CreateScheduleTemplateRequest\x1a!.booking.ScheduleTemplateResponse\x12e\n" +
	"\x18AdminOverrideDaySchedule\x12#.booking.OverrideDayScheduleRequest\x1a$.booking.OverrideDayScheduleResponseB\x11Z\x0f./proto;bookingb\x06proto3"

var (
	file_proto_booking_proto_rawDescOnce sync.Once
	file_proto_booking_proto_rawDescData []byte
)

func file_proto_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)))
	})
	return file_proto_booking_proto_rawDescData
}

var file_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_booking_proto_goTypes = []any{
	(*ListAvailableSlotsRequest)(nil),     // 0: booking.ListAvailableSlotsRequest
	(*TimeSlot)(nil),                      // 1: booking.TimeSlot
	(*ListAvailableSlotsResponse)(nil),    // 2: booking.ListAvailableSlotsResponse
	(*CreateBookingRequest)(nil),          // 3: booking.CreateBookingRequest
	(*BookingResponse)(nil),               // 4: booking.BookingResponse
	(*CancelBookingRequest)(nil),          // 5: booking.CancelBookingRequest
	(*CancelBookingResponse)(nil),         // 6: booking.CancelBookingResponse
	(*ClientBookingsRequest)(nil),         // 7: booking.ClientBookingsRequest
	(*Booking)(nil),                       // 8: booking.Booking
	(*ClientBookingsResponse)(nil),        // 9: booking.ClientBookingsResponse
	(*CreateProcedureRequest)(nil),        // 10: booking.CreateProcedureRequest
	(*ProcedureResponse)(nil),             // 11: booking.ProcedureResponse
	(*AssignProcedureRequest)(nil),        // 12: booking.AssignProcedureRequest
	(*AssignProcedureResponse)(nil),       // 13: booking.AssignProcedureResponse
	(*CreateScheduleTemplateRequest)(nil), // 14: booking.CreateScheduleTemplateRequest
	(*ScheduleTemplateResponse)(nil),      // 15: booking.ScheduleTemplateResponse
	(*OverrideDayScheduleRequest)(nil),    // 16: booking.OverrideDayScheduleRequest
	(*OverrideDayScheduleResponse)(nil),   // 17: booking.OverrideDayScheduleResponse
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
}
var file_proto_booking_proto_depIdxs = []int32{
	18, // 0: booking.TimeSlot.start_time:type_name -> google.protobuf.Timestamp
	18, // 1: booking.TimeSlot.end_time:type_name -> google.protobuf.Timestamp
	1,  // 2: booking.ListAvailableSlotsResponse.slots:type_name -> booking.TimeSlot
	18, // 3: booking.CreateBookingRequest.start_time:type_name -> google.protobuf.Timestamp
	18, // 4: booking.Booking.start_time:type_name -> google.protobuf.Timestamp
	18, // 5: booking.Booking.end_time:type_name -> google.protobuf.Timestamp
	8,  // 6: booking.ClientBookingsResponse.bookings:type_name -> booking.Booking
	0,  // 7: booking.BookingService.ListAvailableSlots:input_type -> booking.ListAvailableSlotsRequest
	3,  // 8: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	5,  // 9: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	7,  // 10: booking.BookingService.ListClientBookings:input_type -> booking.ClientBookingsRequest
	10, // 11: booking.BookingService.AdminCreateProcedure:input_type -> booking.CreateProcedureRequest
	12, // 12: booking.BookingService.AdminAssignProcedure:input_type -> booking.AssignProcedureRequest
	14, // 13: booking.BookingService.AdminCreateScheduleTemplate:input_type -> booking.CreateScheduleTemplateRequest
	16, // 14: booking.BookingService.AdminOverrideDaySchedule:input_type -> booking.OverrideDayScheduleRequest
	2,  // 15: booking.BookingService.ListAvailableSlots:output_type -> booking.ListAvailableSlotsResponse
	4,  // 16: booking.BookingService.CreateBooking:output_type -> booking.BookingResponse
	6,  // 17: booking.BookingService.CancelBooking:output_type -> booking.CancelBookingResponse
	9,  // 18: booking.BookingService.ListClientBookings:output_type -> booking.ClientBookingsResponse
	11, // 19: booking.BookingService.AdminCreateProcedure:output_type -> booking.ProcedureResponse
	13, // 20: booking.BookingService.AdminAssignProcedure:output_type -> booking.AssignProcedureResponse
	15, // 21: booking.BookingService.AdminCreateScheduleTemplate:output_type -> booking.ScheduleTemplateResponse
	17, // 22: booking.BookingService.AdminOverrideDaySchedule:output_type -> booking.OverrideDayScheduleResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_booking_proto_init() }
func file_proto_booking_proto_init() {
	if File_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_proto = out.File
	file_proto_booking_proto_goTypes = nil
	file_proto_booking_proto_depIdxs = nil
}
